spring.datasource.url=jdbc:postgresql://localhost:5432/coop_plus
spring.datasource.username=postgres
spring.datasource.password=131312

spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
api.security.token.secret=${JWT_SECRET:my-secret-key}